% This function plots different parametrizations with the wind speed n the
% x axes

% generator power parametrization
plot_parametrization('fig_power_param',out_store,'P_G', ...
  reference(:, 1),reference(:, 6),static_values(1,:), ...
  static_values(6,:),'Wind speed [m/s]','P [MW]','Generator power', ...
  1e3,1e6,date)

% generator torque parametrization
plot_parametrization('fig_torque_param',out_store,'T_G', ...
  static_values(1,:),static_values(5,:),'Wind speed [m/s]', ...
  'T [MNm]','Generator power',1e6,date)

% pitch parametrization
plot_parametrization('fig_pitch_param',out_store,'pitch', ...
  lookup_Pitch(1,:),lookup_Pitch(5,:),'Wind speed [m/s]', ...
  '$\theta$ [deg.]','Pitch angle',180/pi,date)

% rotational speed
plot_parametrization('fig_omega_param',out_store,'omega_R', ...
  lookup_static_values(1,:),lookup_static_values(2,:), ...
  'Wind speed [m/s]','$\omega$ [rpm]','Rotor rotational speed', ...
  30/pi,date)
