% This function plots different parametrizations with the wind speed n the
% x axes

addpath('\..')
addpath('lookup\')

% generator power parametrization
plot_parametrization_wind('fig_power_param',out_store,'P_G', ...
 lookup_static_values(1,pos_4:pos_25), ...
 lookup_static_values(6,pos_4:pos_25)/1e6,'Wind speed [m/s]','P [MW]', ...
 'Generator power',1e6,date_fig)

% generator torque parametrization
plot_parametrization_wind('fig_torque_param',out_store,'T_G', ...
  lookup_static_values(1,pos_4:pos_25), ...
  lookup_static_values(5,pos_4:pos_25)/1e6,'Wind speed [m/s]','T [MNm]', ...
  'Generator torque',1e6,date_fig)

% pitch parametrization
plot_parametrization_wind('fig_pitch_param',out_store,'pitch', ...
  lookup_Pitch(1,pos_4:pos_25),lookup_Pitch(3,pos_4:pos_25)*180/pi, ...
  'Wind speed [m/s]','$\theta$ [deg.]','Pitch angle',pi/180,date_fig)

% rotational speed
plot_parametrization_wind('fig_omega_param',out_store,'omega_R', ...
  lookup_static_values(1,pos_4:pos_25), ...
  lookup_static_values(2,pos_4:pos_25)*30/pi, ...
  'Wind speed [m/s]','$\omega$ [rpm]','Rotor rotational speed', ...
  pi/30,date_fig)
