% wind speed
plot_time_series('fig_wind_TS',out_store, 'wind', 'Time [s]', ...
  'Wind speed [m/s]', 'Wind speed time serie', 1, date_fig);

% pitch dynamic
plot_time_series('fig_pitch_dynamic', out_store, 'pitch','Time [s]',...
   '$\theta \ [deg.]$', 'Pitch angle time serie', pi/180, date_fig); 

% rotor omega dynamic
plot_time_series('fig_omega_dynamic',out_store,'omega_R','Time [s]',...
  '$\omega_{r}$ [rad/s]', 'Rotor rotational speed', 1, date_fig); 

% power dynamic
plot_time_series2('fig_power_dynamic',out_store,'P_R','P_G', ...
  rotor.P_rated,'Time [s]','P [MW]','Rotor and generator powers', ...
  1e6,'Aero.','Gen.',date_fig)

% torque dynamic
plot_time_series2('fig_torque_dynamic',out_store,'T_G_reference','T_G', ...
  'none','Time [s]','T [MNm]','Generator torque', ...
  1e6,'Ref.','',date_fig)

